/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    colors: {
      'accent-1': 'var(--accent-1)',
      'accent-2': 'var(--accent-2)',
      'accent-3': 'var(--accent-3)',
      'accent-4': 'var(--accent-4)',
      'accent-5': 'var(--accent-5)',
      'accent-6': 'var(--accent-6)',
      'accent-7': 'var(--accent-7)',
      'accent-8': 'var(--accent-8)',
      'accent-9': 'var(--accent-9)',
      'accent-10': 'var(--accent-10)',
      'accent-a1': 'var(--accent-a1)',
      'accent-a2': 'var(--accent-a2)',
      'accent-a3': 'var(--accent-a3)',
      'accent-a4': 'var(--accent-a4)',
      'accent-a5': 'var(--accent-a5)',
      'accent-a6': 'var(--accent-a6)',
      'accent-a7': 'var(--accent-a7)',
      'accent-a8': 'var(--accent-a8)',
      'accent-a9': 'var(--accent-a9)',
      'accent-a10': 'var(--accent-a10)',
      'gray-1': 'var(--gray-1)',
      'gray-2': 'var(--gray-2)',
      'gray-3': 'var(--gray-3)',
      'gray-4': 'var(--gray-4)',
      'gray-5': 'var(--gray-5)',
      'gray-6': 'var(--gray-6)',
      'gray-7': 'var(--gray-7)',
      'gray-8': 'var(--gray-8)',
      'gray-9': 'var(--gray-9)',
      'gray-10': 'var(--gray-10)',
      'gray-11': 'var(--gray-11)',
      'gray-12': 'var(--gray-12)',
      'red-1': 'var(--red-1)',
      'red-2': 'var(--red-2)',
      'red-3': 'var(--red-3)',
      'red-4': 'var(--red-4)',
      'red-5': 'var(--red-5)',
      'red-6': 'var(--red-6)',
      'red-7': 'var(--red-7)',
      'red-8': 'var(--red-8)',
      'red-9': 'var(--red-9)',
      'red-10': 'var(--red-10)',
      'red-11': 'var(--red-11)',
      'red-12': 'var(--red-12)',
      'green-1': 'var(--green-1)',
      'green-2': 'var(--green-2)',
      'green-3': 'var(--green-3)',
      'green-4': 'var(--green-4)',
      'green-5': 'var(--green-5)',
      'green-6': 'var(--green-6)',
      'green-7': 'var(--green-7)',
      'green-8': 'var(--green-8)',
      'green-9': 'var(--green-9)',
      'green-10': 'var(--green-10)',
      'green-11': 'var(--green-11)',
      'green-12': 'var(--green-12)',
    },
    extend: {},
  },
  plugins: [],
};
